# This YAML is the default template and can be modified based on this 
---
version: 2.0
steps:
  PRE_BUILD:
  - checkout:
      name: "checkout"
      inputs:
        scm: "codehub"
        url: "bitbucket.org:rappi-test/rappi-test.git"
        user: "CruzDvd1972"
        password: "Andrea1980$"
        branch: "main"
        lfs: false
        submodule: false
  BUILD:
  - sh:
      name: "sh"
      inputs:
        command: "echo hello"
